### ISSUE TITLE
It's impossible to use autocomplete of methods in WebStorm

### ISSUE THREAD

**Issue by aivus** [athombv/eslint-config-athom#29]
I'm not good in TypeScript, but I suppose autocompletion should work not only for the classnames.
Currently autocompletion for methods doesn't work:

![image](https://user-images.githubusercontent.com/1021703/79020782-74935900-7b82-11ea-8a6a-4a78bd89b243.png)

When I'm trying to override any method of `Homey.Device`

![image](https://user-images.githubusercontent.com/1021703/79020747-5cbbd500-7b82-11ea-9d25-bf2873e8b874.png)

**Comment by tjallingt** [comment]
Thanks for the bug report, I'll look into it!
Do you have a tsconfig? if so can you share it here?

**Comment by aivus** [comment]
I'm closing it because autocomplete suddenly started working. 🤷‍♂️

Thanks

**Comment by tjallingt** [comment]
That's great! But it's also terrible since we have no idea what caused it :(
Be sure to reach out if it happens again and/or you have any ideas for how we can prevent it!
